### ISSUE TITLE
It doesn't show the the trade pop-up in POE2

### ISSUE THREAD

**Issue by bleeblee666** [Morph21/MercuryTrade-Community-Fork#165]
The app says it's already 1.36 and the taskbar is shown in game, open test is fine, but the real trade message doesn't make the pop-up shown
I also enabled POE2 support, and locate the right folder, but it resets to uncheck and located to my POE1 folder after restart app.

Do I need to download the file and run it in a seperated folder? I had no problem when using is in POE1, and java already installed.

Thanks for updating this app

**Comment by bleeblee666** [comment]
Update:
I delete the folder in appdata, did a clean install, it's working for trade messages now. But there's another issue, I lowered the notification volume, it also reset after restart the app. And poe 2 support tick box also reset.
Another question is what if I want to play poe 1 for next league,  do I just change folder selection or it will automatically recognize?

**Comment by Morph21** [comment]
You need to press save after changing things inside settings for it to be saved, that's why after restart your checkbox did uncheck and slider moved back.

Location of tab name which is shown after clicking is tied to grid location when you do set it up (grid icon on taskbar, need to save after changing it too) it cannot be moved in any other way.

If you want to use it for Poe 1 again you will need to change Poe folder location and Poe 2 support to disabled and save settings for it to work there

**Comment by bleeblee666** [comment]
I did save before close settings, here is what's happening now: the item grid position, panels position all saved. Only things that reset every time are something like poe2 support check, sound levels, and Hotkeys for response buttons.

**Comment by Morph21** [comment]
@bleeblee666 issue with saving settings will be resolved in today's release but it will come later.

For now you can follow this steps for it to be fixed for you
1. Close MercuryTrade if it's already running
2. Start it again and wait for load to finish
3. Go to settings
4. Click on choose language input
5. From dropdown list chose the one that you are using already or select any other one then select yours
6. Press Save
