### ISSUE TITLE
[BUG] - Incoming messages with Korean nickname but english client

### ISSUE THREAD

**Issue by pwilkowski** [Morph21/MercuryTrade-Community-Fork#35]
**Describe the bug**
I don't get notified when korean or other weird characters are in buyers nick.

**To Reproduce**
1. Post some item on account 1.
2. Create character with korean name on account 2
3. Try to buy something from your first account by being on character with korean nick

**Expected behavior**
Notification pops up

**Desktop (please complete the following information):**
 - 1.1.4

**Comment by Morph21** [comment]
Hello, thank you for your feedback. I'm already working on this issue. It will be done in chunks for each site like poeapp/poetrade/pathofexile.com/trade.

But keep in mind that if Korean player will whisper you while playing on Korean client messages won't pop up because of "Korean government privacy policy"*.


* Korean government privacy policy - states that private messages cannot be collected/saved etc. So they are not saved in client.txt file where PoE saves each incoming/outgoing messages

**Comment by Morph21** [comment]
@pwilkowski Could you post here an example message which is send in the situation you described?

**Comment by pwilkowski** [comment]
I use normal EU english client, but from what are you saying, korean whispers are not saved to client.txt and that is why it's not working?

And I just confirmed, people from korean realm aren't listed, damn. I do not see whispers from korean players in client.txt
Only messeges 
```
2020/10/31 16:57:07 879347031 ba9 [INFO Client 17504] : XXXXXXXX has joined the area.
2020/10/31 16:57:18 879358312 ba9 [INFO Client 17504] : Trade accepted.
2020/10/31 16:57:21 879361234 ba9 [INFO Client 17504] @To XXXXXXXXX: ty
2020/10/31 16:57:23 879363250 ba9 [INFO Client 17504] : XXXXXX has left the area.
```

Sadge

**Comment by Morph21** [comment]
Yea, sadly it's the case. Im working on properly displaying korean names and showing outcoming messages to korean players (which are logged into client.txt) but because of Korean goverment policy there won't be a single app which can show this messages :(

**Comment by pwilkowski** [comment]
Guess we can close this issue, funny thing is, their nicks are logged in client.txt but only when joining/leaving party.  But not when whispering

**Comment by Morph21** [comment]
Yea, it's like "Private message should be private" or whatever
